### ISSUE TITLE
Similarity to rust-lang/rust-analyzer

### ISSUE THREAD

**Issue by Tastaturtaste** [kitamstudios/rust-analyzer.vs#11]
Are you in any way affiliated with the [rust-analyzer plugin for visual studio code](https://github.com/rust-lang/rust-analyzer)? If so it would be good to show that in your README.

As it is I have the impression of a intentionally misleading name to draw in users.

**Comment by lnicola** [comment]
> i have changed the name to rust-analyzer.vs and will be adding a VS logo into the RA logo. would that suffice?

That doesn't scream "not official" to me, TBH. I'd personally prefer a blurb like "This plugin is not affiliated with the `rust-analyzer` project.", which seems more fair.

**Comment by parthopdas** [comment]
@lnicola your suggestion is fair to ensure that team doesn't get unwarranted bugs filed against them.

for sure i don't want to name it something jazzy to give the impression this plugin does some extraordinary when pretty much all it does is expose rust-analyzer.exe with rest of the rust tool chain. 

i'll push that out in the next release scheduled in a couple of days.

**Comment by lnicola** [comment]
I think it's more likely that you'll get issues for bugs in RA itself. I've expanded my comment above to point this out.

**Comment by parthopdas** [comment]
makes sense, i'll pass them over as and when i can prove they belong to the rust toolchain.

**Comment by Tastaturtaste** [comment]
> @Tastaturtaste this extension surfaces the rust language server in VS 2022 i.e. the rust-analyzer.exe binary. it is very much the rust-analyzer and therefore rust language team's work. very small part is my own work.
> 
> so while not affiliated with the vscode version, it is parallel to the vscode version.
> 
> i have changed the name to rust-analyzer.vs and will be adding a VS logo into the RA logo. would that suffice?

@lnicola has basically said what I think on the topic. I would at least expect a prominent disclaimer in the Readme and on the plugins market page that this project is not affiliated with rust-lang/rust-analyzer. Even then I expect many people will get confused by the naming.

**Comment by parthopdas** [comment]
@lnicola @Tastaturtaste please check https://github.com/kitamstudios/rust-analyzer.vs - README updated.

it will also get reflected on the marketplace with the next release as the same readme is used.

**Comment by lnicola** [comment]
I would have put it like:

> This extension is not affiliated with [rust-lang/rust-analyzer](https://github.com/rust-lang/rust-analyzer/), and just uses rust-analyzer as an LSP server, together with the installed [Rust toolchain](https://github.com/rust-lang/). For a list of features, please see the [official site](https://rust-analyzer.github.io/) [and manual](https://rust-analyzer.github.io/manual.html). To report a bug that doesn't seem to be specific to this Visual Studio extension, head to the [rust-analyzer issue tracker](https://github.com/rust-lang/rust-analyzer/issues).

**Comment by parthopdas** [comment]
i am going to leave this line out. rest i'll i'll steal from yours.

> To report a bug that doesn't seem to be specific to this Visual Studio extension, head to the [rust-analyzer issue tracker](https://github.com/rust-lang/rust-analyzer/issues).

it is not the user's job to debug who the issue belongs to. if they hit something they need to file it wherever they can - you i can then figure out who really owns the bug.

**Comment by parthopdas** [comment]
@lnicola done, please check https://github.com/kitamstudios/rust-analyzer.vs

**Comment by parthopdas** [comment]
ok thumbs up from both of you. closing it. please reactivate or file new as you encounter new issues. thank you guys!
