### ISSUE TITLE
Passing arguments to run/debug

### ISSUE THREAD

**Issue by r1sc** [kitamstudios/rust-analyzer.vs#13]
Maybe I missed it, is it possible? If not it would be great if we could do that somehow.

EDIT: By the way, nice job on the extension! :)

**Comment by parthopdas** [comment]
thank you. you comment makes all the effort worth it ❤️

yes it is possible
1. right click on cargo.toml and click properties and you can set it like this 
   ![image](https://user-images.githubusercontent.com/2140460/222750140-73a1a5cf-dc28-436e-a707-8f6fda88fa8c.png)

1. for examples, you can right click on the example file and set it simillarly

**Comment by parthopdas** [comment]
i have been putting off writing the documentation, which i will as soon as the next release goes out.

**Comment by parthopdas** [comment]
also @r1sc if you do cross platform development (e.g. build on windows target wsl2) i would like to hear your thoughts on #10 i.e. what would an ideal experience look like?

**Comment by parthopdas** [comment]
please reactivate if you have additional feedback
