### ISSUE TITLE
Type syntax coloring

### ISSUE THREAD

**Issue by r1sc** [kitamstudios/rust-analyzer.vs#17]
Primitive types are colored, but complex types such as Vec<> is not. Using default Visual Studio light template.

Visual Studio 2022:
![bild](https://user-images.githubusercontent.com/629669/226901948-4dcb5ae1-81a0-4e65-b257-fabb8e24948b.png)

Visual Studio Code:
![bild](https://user-images.githubusercontent.com/629669/226902168-ee0a987e-a80c-4951-ac59-0b58d0f3cdf9.png)

**Comment by parthopdas** [comment]
it seems to work for me on the latest release -
![image](https://user-images.githubusercontent.com/2140460/227100748-0d0314c1-927a-406d-acc4-034579fec5b9.png)

would you mind providing some more info:
1. what version of the extension do you have? if not the latest, can you try the latest and let me know.
1. does it appear after a 30 seconds or so (for large projects rls takes a while to get going)
1. are there any "rust-analyzer" related errors in Output > rustanalyzer.vs window (this contains the realtime logging from the extension)

**Comment by parthopdas** [comment]
and stay tuned for Test Explorer integration (running / debug unit tests) as well as Cross Platform rust build / debug using WSL2.

**Comment by r1sc** [comment]
I meant of course https://marketplace.visualstudio.com/items?itemName=kitamstudios.RustAnalyzer&ssr=false 😋 So the published build didn't have it as I understand it?
