### ISSUE TITLE
How to Launch a Hello World ? 

### ISSUE THREAD

**Issue by tomaszkot** [kitamstudios/rust-analyzer.vs#20]
![image](https://user-images.githubusercontent.com/2432291/229999787-bae82334-0fc9-4c34-8670-60d78157ac18.png)

I get:

---------------------------
Microsoft Visual Studio
---------------------------
Please select a valid startup item
---------------------------
OK   
---------------------------

**Comment by parthopdas** [comment]
if this project was created by cargo, you will need to open c:\users\tomko\project_name in VS

let me know how it goes.

![image](https://user-images.githubusercontent.com/2140460/230473177-7992955c-51ed-406e-b721-aca5cfad36ca.png)

**Comment by tomaszkot** [comment]
Yes, that worked, thanks!

**Comment by parthopdas** [comment]
closing this. please reactivate as necessary.
