### ISSUE TITLE
Incorrect colorization of methods

### ISSUE THREAD

**Issue by nolekev1214** [kitamstudios/rust-analyzer.vs#21]
Methods are not given a coloring, and are instead displayed as white text. Consider giving methods the same color as functions.

![image](https://user-images.githubusercontent.com/10646831/233852429-440755f8-2d4b-45a9-b0c6-ebbce4f6cc8c.png)

In the above image, the method Iterator::collect(self) is not given the same color as the function std::env::args().

**Comment by parthopdas** [comment]
this is odd. are you able to F12 navigate to the method / class definitions?

**Comment by nolekev1214** [comment]
After double checking it today everything seemed to be colored as expected. Potentially the LSP had not finished parsing my code.

**Comment by nolekev1214** [comment]
I appear to have gotten my explanation backwards. Colorization only breaks after the LSP has fully analyzed the code: 
![image](https://user-images.githubusercontent.com/10646831/236275448-97d25cc9-92ef-4b63-b2ad-ecaf130c9ebb.png)

**Comment by nolekev1214** [comment]
Turns out the colorizer is just completely broken on my Visual Studio 2022.

**Comment by parthopdas** [comment]
hmm...

would you mind replacing the rust-analyzer.exe with the latest version from rust-lang/rust-analyzer project and checking if that is still the case?

if so, i'll push out an update by tonight.

**Comment by parthopdas** [comment]
r-a has been update since. please reactive as necessary.
