### ISSUE TITLE
rust-analyzer.vs breaks running 100% C++ CMake projects

### ISSUE THREAD

**Issue by COLAMAroro** [kitamstudios/rust-analyzer.vs#24]
Hello

I wanted to work on a new project, a 100% C++ Project, built with CMake.
However, rust-analyzer.vs complains about "program" not being set in launch configuration

![image](https://github.com/kitamstudios/rust-analyzer.vs/assets/12484955/9feb7b4a-d28e-4b75-b8ad-19054571fa03)

The only thing I did was create a new CMake based project, generate the CMake configuration, and run the target binary

**Comment by parthopdas** [comment]
this is definitely odd. otoh it may help fix a bug i have been chasing for a while.

please can you attach the project. i'll get to this by max tomorrow.

**Comment by COLAMAroro** [comment]
Sure

I've uploaded a just fresh CMake Project here: [colamaroro/cmake-demo](https://github.com/colamaroro/cmake-demo)

**Comment by parthopdas** [comment]
thanks. running late on this. should be done by today,

**Comment by COLAMAroro** [comment]
Take your time, these are all personal projects with no timeline :) 
(And I can just turn the extension off when working on CMake projects. Annoying but nothing near the end of the world)

**Comment by parthopdas** [comment]
pushed in a workaround. once CI finishes please install from https://www.vsixgallery.com/extension/KS.RustAnalyzer.3a91e56b-fb28-4d85-b572-ec964abf8e31/

and let me know if the fix is fine for you.

**Comment by parthopdas** [comment]
released to vs marketplace. pls reactivate if not fixed.
