### ISSUE TITLE
Debugging is broken since 2.0.160

### ISSUE THREAD

**Issue by Axel-Reactor** [kitamstudios/rust-analyzer.vs#36]
![image](https://github.com/kitamstudios/rust-analyzer.vs/assets/127901757/ead72768-b1ee-4d65-bf3c-5147f1fcaaa6)

**Comment by Axel-Reactor** [comment]
Ignore this, I didn't have the launch configuration set correctly. The error message could use improvements though.

**Comment by parthopdas** [comment]
@Axel-Reactor you dont need the launch configuration.

if you let me know a bit more i can put it through th enext release, due in a day or so.

**Comment by parthopdas** [comment]
@Axel-Reactor gentle reminder!
