### ISSUE TITLE
Documentation overlay seems to be broken

### ISSUE THREAD

**Issue by DerickGamer** [kitamstudios/rust-analyzer.vs#37]
Quite simple: the overlay that appears when you put the cursor over items showing the documentation comments ain't doing it well.
VS Code for comparison:
![image](https://github.com/kitamstudios/rust-analyzer.vs/assets/72350837/0b5ddaf7-97c6-42f8-97ba-85d099342a2e)
Visual Studio
![image](https://github.com/kitamstudios/rust-analyzer.vs/assets/72350837/a6b976d4-f4a8-4cc9-ab4a-3ae0d901a01e)

**Comment by parthopdas** [comment]
Unfortunately this has always been the case. Visual Studio 2022 only shows the documentation as text that it queries from RLS.

**Comment by DerickGamer** [comment]
I see... Well, then, can you do something about this?
![image](https://github.com/kitamstudios/rust-analyzer.vs/assets/72350837/cfc25ba2-1a9b-4626-bde8-c5842d65ea5b)
