### ISSUE TITLE
Question: how to debug test code?

### ISSUE THREAD

**Issue by nneesshh** [kitamstudios/rust-analyzer.vs#38]
where is the "test explorer"?

**Comment by parthopdas** [comment]
My apologies missed getting the notification for this.

What you are looking for is here: [Run, debug & manage unit tests from test explorer.](https://youtu.be/pE1Vr2zVCbg?t=379) - specifically note the rust nightly requirement.

Please reopen if you still run into issues.

The project README has detailed video documentation.
