### ISSUE TITLE
Choose a suitable licence applicable to code

### ISSUE THREAD

**Issue by simonsan** [kitamstudios/rust-analyzer.vs#40]
There is a website: https://choosealicense.com/ that can help to choose a licence for your code. The licence of this repository seems like a pretty unusual one for code. Why is that?

**Comment by parthopdas** [comment]
Personal principles. Happy to update as necessary. What's the issue?

**Comment by parthopdas** [comment]
Dude what is the issue you are facing? Happy to update license or anything based on that. 

Don't give me some lawyer document. I wrote the code I get to apply whatever license strikes my fancy.

**Comment by parthopdas** [comment]
Okay. If you are facing issues with this licence (eg your employer wont allow OSS with this license to be used) like I said I am happy to change the license.

A metaphysical discussion on licenses & lack of specifics is honestly disappointing.

If you do face issues in the future - adoption or other technical issues - reactivate, even better send a PR acceptable to your employer.
