### ISSUE TITLE
Can't build/debug program

### ISSUE THREAD

**Issue by Blue741** [kitamstudios/rust-analyzer.vs#53]
Hello there!
I have trouble debugging my small example program.
My steps:
1. Open VS22
2. File > Open > Folder and select my Example
3. Right click on main.rs > Set as start element
4. F5 to debug

My result:
![image](https://github.com/user-attachments/assets/f1da8bc0-23c8-43dc-8e31-fb05cb3d030d)

My [Build log.txt](https://github.com/user-attachments/files/16604384/Log.txt)

The code I'm trying to build:
![image](https://github.com/user-attachments/assets/7fe062c0-03f4-4624-9b2b-a118aef213e3)

My versions (if needed):
VS Community 2022 version: 17.11.0
Rust-analyzer version: 2.0.187
cargo 1.80.0 (376290515 2024-07-16)
rustc 1.80.0 (051478957 2024-07-21)

Thank you in advance!

**Comment by unrenormalizable** [comment]
i'll need to fix this bug.

can you try setting the cargo.toml as startup and then F5ing?

**Comment by Blue741** [comment]
Yeah, give me a moment.

**Comment by Blue741** [comment]
Interesting, now it works even though I tried it before.
Ok, thank you very much!
