### ISSUE TITLE
Unable to remove via extensions list due to prerequisite check

### ISSUE THREAD

**Issue by Jake-Jensen** [kitamstudios/rust-analyzer.vs#56]
Issue: Can't uninstall extension through the extensions list when it can't find rustup, because for some stupid reason you force close the IDE on us instead of just issuing an extension warning. 

![image](https://github.com/user-attachments/assets/3c362294-1ed3-4f49-ae72-b0651826ce3c)

To reproduce:
Install this extension.
Remove / fail to install rustup
Restart IDE

Choices are to either reinstall rustup, just to remove this extension, or file manipulation, to remove it from the IDE entirely.

**Comment by parthopdas** [comment]
Rustup is unavailable in the path. What rust developmentare you doing exactly? Either fix that or delete the extention from the extension folder.

Or send a PR fixing this issue 

Thwrw is already an issue tracking this. I'll get to it 

I published this extension after building it for myself and add features based my my requirements. This is 1/20 of an engineer working on it not a multinational corp.when

**Comment by Jake-Jensen** [comment]
Whatever rust development I choose to.
That's a lot of excuses for a simple fix. Like literally the time it took to write that, could have just went in to the extension and removed the line forcing the IDE to restart. 

I'm fully aware of how to fix the problem, eg removing your extension, as I outlined that in the original issue. 

If you don't want to correctly maintain an extension, don't publish it. Not that complex really.
